<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="26" passed="9" failed="2" skipped="15">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-24T14:36:04 IST" name="Default suite" finished-at="2022-11-24T14:36:05 IST" duration-ms="859">
    <groups>
    </groups>
    <test started-at="2022-11-24T14:36:04 IST" name="Default test" finished-at="2022-11-24T14:36:05 IST" duration-ms="859">
      <class name="com.myapp.spring.NumberSubscriberVerification">
        <test-method is-config="true" signature="startPublisherExecutorService()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="startPublisherExecutorService" finished-at="2022-11-24T14:36:04 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startPublisherExecutorService -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="setUp" finished-at="2022-11-24T14:36:04 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec201_blackbox_mustSignalDemandViaSubscriptionRequest()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="required_spec201_blackbox_mustSignalDemandViaSubscriptionRequest" finished-at="2022-11-24T14:36:04 IST" duration-ms="69" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec201_blackbox_mustSignalDemandViaSubscriptionRequest -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="setUp" finished-at="2022-11-24T14:36:04 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnComplete()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnComplete" finished-at="2022-11-24T14:36:04 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnComplete -->
        <test-method signature="required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnError()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnError" finished-at="2022-11-24T14:36:04 IST" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnError -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="setUp" finished-at="2022-11-24T14:36:04 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="setUp" finished-at="2022-11-24T14:36:04 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec205_blackbox_mustCallSubscriptionCancelIfItAlreadyHasAnSubscriptionAndReceivesAnotherOnSubscribeSignal()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:04 IST" name="required_spec205_blackbox_mustCallSubscriptionCancelIfItAlreadyHasAnSubscriptionAndReceivesAnotherOnSubscribeSignal" finished-at="2022-11-24T14:36:05 IST" duration-ms="143" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Subscriber org.reactivestreams.tck.SubscriberWhiteboxVerification$BlackboxSubscriberProxy@7e990ed7 illegally called `subscription.request(10)`!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Subscriber org.reactivestreams.tck.SubscriberWhiteboxVerification$BlackboxSubscriberProxy@7e990ed7 illegally called `subscription.request(10)`!
at org.testng.Assert.fail(Assert.java:99)
at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:222)
at org.reactivestreams.tck.SubscriberBlackboxVerification$4$1.request(SubscriberBlackboxVerification.java:219)
at com.myapp.spring.NumberSubscriber.onSubscribe(NumberSubscriber.java:13)
at org.reactivestreams.tck.SubscriberWhiteboxVerification$BlackboxSubscriberProxy.onSubscribe(SubscriberWhiteboxVerification.java:610)
at org.reactivestreams.tck.SubscriberBlackboxVerification$4.<init>(SubscriberBlackboxVerification.java:215)
at org.reactivestreams.tck.SubscriberBlackboxVerification.required_spec205_blackbox_mustCallSubscriptionCancelIfItAlreadyHasAnSubscriptionAndReceivesAnotherOnSubscribeSignal(SubscriberBlackboxVerification.java:212)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec205_blackbox_mustCallSubscriptionCancelIfItAlreadyHasAnSubscriptionAndReceivesAnotherOnSubscribeSignal -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithPrecedingRequestCall()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithPrecedingRequestCall" finished-at="2022-11-24T14:36:05 IST" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithPrecedingRequestCall -->
        <test-method signature="required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithoutPrecedingRequestCall()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithoutPrecedingRequestCall" finished-at="2022-11-24T14:36:05 IST" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithoutPrecedingRequestCall -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithPrecedingRequestCall()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithPrecedingRequestCall" finished-at="2022-11-24T14:36:05 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithPrecedingRequestCall -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithoutPrecedingRequestCall()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithoutPrecedingRequestCall" finished-at="2022-11-24T14:36:05 IST" duration-ms="28" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithoutPrecedingRequestCall -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec213_blackbox_onError_mustThrowNullPointerExceptionWhenParametersAreNull()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="required_spec213_blackbox_onError_mustThrowNullPointerExceptionWhenParametersAreNull" finished-at="2022-11-24T14:36:05 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec213_blackbox_onError_mustThrowNullPointerExceptionWhenParametersAreNull -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec213_blackbox_onNext_mustThrowNullPointerExceptionWhenParametersAreNull()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="required_spec213_blackbox_onNext_mustThrowNullPointerExceptionWhenParametersAreNull" finished-at="2022-11-24T14:36:05 IST" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[onNext(null) did not throw NullPointerException expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: onNext(null) did not throw NullPointerException expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.reactivestreams.tck.SubscriberBlackboxVerification$10.run(SubscriberBlackboxVerification.java:362)
at org.reactivestreams.tck.SubscriberBlackboxVerification.blackboxSubscriberWithoutSetupTest(SubscriberBlackboxVerification.java:449)
at org.reactivestreams.tck.SubscriberBlackboxVerification.required_spec213_blackbox_onNext_mustThrowNullPointerExceptionWhenParametersAreNull(SubscriberBlackboxVerification.java:345)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec213_blackbox_onNext_mustThrowNullPointerExceptionWhenParametersAreNull -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="required_spec213_blackbox_onSubscribe_mustThrowNullPointerExceptionWhenParametersAreNull()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="required_spec213_blackbox_onSubscribe_mustThrowNullPointerExceptionWhenParametersAreNull" finished-at="2022-11-24T14:36:05 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- required_spec213_blackbox_onSubscribe_mustThrowNullPointerExceptionWhenParametersAreNull -->
        <test-method signature="untested_spec202_blackbox_shouldAsynchronouslyDispatch()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec202_blackbox_shouldAsynchronouslyDispatch" finished-at="2022-11-24T14:36:05 IST" duration-ms="2" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec202_blackbox_shouldAsynchronouslyDispatch(SubscriberBlackboxVerification.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec202_blackbox_shouldAsynchronouslyDispatch -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec204_blackbox_mustConsiderTheSubscriptionAsCancelledInAfterRecievingOnCompleteOrOnError()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec204_blackbox_mustConsiderTheSubscriptionAsCancelledInAfterRecievingOnCompleteOrOnError" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec204_blackbox_mustConsiderTheSubscriptionAsCancelledInAfterRecievingOnCompleteOrOnError(SubscriberBlackboxVerification.java:207)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec204_blackbox_mustConsiderTheSubscriptionAsCancelledInAfterRecievingOnCompleteOrOnError -->
        <test-method signature="untested_spec206_blackbox_mustCallSubscriptionCancelIfItIsNoLongerValid()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec206_blackbox_mustCallSubscriptionCancelIfItIsNoLongerValid" finished-at="2022-11-24T14:36:05 IST" duration-ms="3" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec206_blackbox_mustCallSubscriptionCancelIfItIsNoLongerValid(SubscriberBlackboxVerification.java:241)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec206_blackbox_mustCallSubscriptionCancelIfItIsNoLongerValid -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec207_blackbox_mustEnsureAllCallsOnItsSubscriptionTakePlaceFromTheSameThreadOrTakeCareOfSynchronization()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec207_blackbox_mustEnsureAllCallsOnItsSubscriptionTakePlaceFromTheSameThreadOrTakeCareOfSynchronization" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec207_blackbox_mustEnsureAllCallsOnItsSubscriptionTakePlaceFromTheSameThreadOrTakeCareOfSynchronization(SubscriberBlackboxVerification.java:246)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec207_blackbox_mustEnsureAllCallsOnItsSubscriptionTakePlaceFromTheSameThreadOrTakeCareOfSynchronization -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec208_blackbox_mustBePreparedToReceiveOnNextSignalsAfterHavingCalledSubscriptionCancel()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec208_blackbox_mustBePreparedToReceiveOnNextSignalsAfterHavingCalledSubscriptionCancel" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec208_blackbox_mustBePreparedToReceiveOnNextSignalsAfterHavingCalledSubscriptionCancel(SubscriberBlackboxVerification.java:252)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec208_blackbox_mustBePreparedToReceiveOnNextSignalsAfterHavingCalledSubscriptionCancel -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec211_blackbox_mustMakeSureThatAllCallsOnItsMethodsHappenBeforeTheProcessingOfTheRespectiveEvents()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec211_blackbox_mustMakeSureThatAllCallsOnItsMethodsHappenBeforeTheProcessingOfTheRespectiveEvents" finished-at="2022-11-24T14:36:05 IST" duration-ms="11" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec211_blackbox_mustMakeSureThatAllCallsOnItsMethodsHappenBeforeTheProcessingOfTheRespectiveEvents(SubscriberBlackboxVerification.java:308)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec211_blackbox_mustMakeSureThatAllCallsOnItsMethodsHappenBeforeTheProcessingOfTheRespectiveEvents -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec212_blackbox_mustNotCallOnSubscribeMoreThanOnceBasedOnObjectEquality()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec212_blackbox_mustNotCallOnSubscribeMoreThanOnceBasedOnObjectEquality" finished-at="2022-11-24T14:36:05 IST" duration-ms="8" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec212_blackbox_mustNotCallOnSubscribeMoreThanOnceBasedOnObjectEquality(SubscriberBlackboxVerification.java:313)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec212_blackbox_mustNotCallOnSubscribeMoreThanOnceBasedOnObjectEquality -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec213_blackbox_failingOnSignalInvocation()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec213_blackbox_failingOnSignalInvocation" finished-at="2022-11-24T14:36:05 IST" duration-ms="3" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec213_blackbox_failingOnSignalInvocation(SubscriberBlackboxVerification.java:318)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec213_blackbox_failingOnSignalInvocation -->
        <test-method signature="untested_spec301_blackbox_mustNotBeCalledOutsideSubscriberContext()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec301_blackbox_mustNotBeCalledOutsideSubscriberContext" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec301_blackbox_mustNotBeCalledOutsideSubscriberContext(SubscriberBlackboxVerification.java:401)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec301_blackbox_mustNotBeCalledOutsideSubscriberContext -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec308_blackbox_requestMustRegisterGivenNumberElementsToBeProduced()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec308_blackbox_requestMustRegisterGivenNumberElementsToBeProduced" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec308_blackbox_requestMustRegisterGivenNumberElementsToBeProduced(SubscriberBlackboxVerification.java:406)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec308_blackbox_requestMustRegisterGivenNumberElementsToBeProduced -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec310_blackbox_requestMaySynchronouslyCallOnNextOnSubscriber()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec310_blackbox_requestMaySynchronouslyCallOnNextOnSubscriber" finished-at="2022-11-24T14:36:05 IST" duration-ms="2" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec310_blackbox_requestMaySynchronouslyCallOnNextOnSubscriber(SubscriberBlackboxVerification.java:411)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec310_blackbox_requestMaySynchronouslyCallOnNextOnSubscriber -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec311_blackbox_requestMaySynchronouslyCallOnCompleteOrOnError()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec311_blackbox_requestMaySynchronouslyCallOnCompleteOrOnError" finished-at="2022-11-24T14:36:05 IST" duration-ms="2" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec311_blackbox_requestMaySynchronouslyCallOnCompleteOrOnError(SubscriberBlackboxVerification.java:416)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec311_blackbox_requestMaySynchronouslyCallOnCompleteOrOnError -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec314_blackbox_cancelMayCauseThePublisherToShutdownIfNoOtherSubscriptionExists()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec314_blackbox_cancelMayCauseThePublisherToShutdownIfNoOtherSubscriptionExists" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec314_blackbox_cancelMayCauseThePublisherToShutdownIfNoOtherSubscriptionExists(SubscriberBlackboxVerification.java:421)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec314_blackbox_cancelMayCauseThePublisherToShutdownIfNoOtherSubscriptionExists -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec315_blackbox_cancelMustNotThrowExceptionAndMustSignalOnError()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec315_blackbox_cancelMustNotThrowExceptionAndMustSignalOnError" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec315_blackbox_cancelMustNotThrowExceptionAndMustSignalOnError(SubscriberBlackboxVerification.java:426)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec315_blackbox_cancelMustNotThrowExceptionAndMustSignalOnError -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="setUp" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="untested_spec316_blackbox_requestMustNotThrowExceptionAndMustOnErrorTheSubscriber()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="untested_spec316_blackbox_requestMustNotThrowExceptionAndMustOnErrorTheSubscriber" finished-at="2022-11-24T14:36:05 IST" duration-ms="2" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not verified using this TCK.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not verified using this TCK.
at org.reactivestreams.tck.SubscriberBlackboxVerification.notVerified(SubscriberBlackboxVerification.java:507)
at org.reactivestreams.tck.SubscriberBlackboxVerification.untested_spec316_blackbox_requestMustNotThrowExceptionAndMustOnErrorTheSubscriber(SubscriberBlackboxVerification.java:431)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- untested_spec316_blackbox_requestMustNotThrowExceptionAndMustOnErrorTheSubscriber -->
        <test-method is-config="true" signature="shutdownPublisherExecutorService()[pri:0, instance:com.myapp.spring.NumberSubscriberVerification@5d0a1059]" started-at="2022-11-24T14:36:05 IST" name="shutdownPublisherExecutorService" finished-at="2022-11-24T14:36:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutdownPublisherExecutorService -->
      </class> <!-- com.myapp.spring.NumberSubscriberVerification -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
